name: btc-ccs
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base >=4.5,<4.6   # matches bioconda's current CNTools build
  - r-data.table
  - r-optparse
  - r-stringr
  - r-dplyr
  - r-tibble
  - bioconductor-cntools
